// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// execute_estarfm_job
void execute_estarfm_job(CharacterVector input_filenames, CharacterVector input_resolutions, IntegerVector input_dates, IntegerVector pred_dates, CharacterVector pred_filenames, IntegerVector pred_area);
RcppExport SEXP _ImageFusion_execute_estarfm_job(SEXP input_filenamesSEXP, SEXP input_resolutionsSEXP, SEXP input_datesSEXP, SEXP pred_datesSEXP, SEXP pred_filenamesSEXP, SEXP pred_areaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type input_filenames(input_filenamesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type input_resolutions(input_resolutionsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type input_dates(input_datesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pred_dates(pred_datesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pred_filenames(pred_filenamesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pred_area(pred_areaSEXP);
    execute_estarfm_job(input_filenames, input_resolutions, input_dates, pred_dates, pred_filenames, pred_area);
    return R_NilValue;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _ImageFusion_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ImageFusion_execute_estarfm_job", (DL_FUNC) &_ImageFusion_execute_estarfm_job, 6},
    {"_ImageFusion_rcpp_hello_world", (DL_FUNC) &_ImageFusion_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ImageFusion(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
